### ISSUE TITLE
enhanced_searchability-mc1.20.4-1.0.1-build.11 v1.0.1 Crashes in 1.20.4

### ISSUE THREAD

**Issue by UltimatChamp** [MrMelon54/enhanced_searchability#1]
- **Logs** (With Only **Enhanced Searchability** and its dependencies- Architectuary API, Cloth Config API and Fabric API):
  https://mclo.gs/EIMumus

- **More Logs** (In a more modded scenario, since, its contains some extra info):
  https://mclo.gs/nVY9c0D

Both of these happened after opening Multiplayer Server List! The crash also happens in the Resource-pack screen!

**Comment by mrmelon54** [comment]
Probably fixed now

**Comment by UltimatChamp** [comment]
Not fixed :c

**Log:** https://mclo.gs/Q5aDPYO
**Crash Report:** https://mclo.gs/iln7PqR
